/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import logica.MostrarPlantilla;

/**
 *
 * @author Miguel
 */
public class CambioPlantilla extends javax.swing.JFrame {

    /**
     * Creates new form CambioPlantilla
     */
    public CambioPlantilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_plantilla1 = new javax.swing.JButton();
        btn_plantilla2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        btn_plantilla1.setText("Plantilla1");
        btn_plantilla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plantilla1ActionPerformed(evt);
            }
        });

        btn_plantilla2.setText("Plantilla2");
        btn_plantilla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plantilla2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btn_plantilla1)
                .addGap(49, 49, 49)
                .addComponent(btn_plantilla2)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_plantilla1)
                    .addComponent(btn_plantilla2))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_plantilla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plantilla1ActionPerformed
       Plantilla1 plantilla1 = new Plantilla1(MostrarPlantilla.fndCabecera, 
               MostrarPlantilla.imgCabecera,
                    MostrarPlantilla.fndPrincipal, 
               MostrarPlantilla.imgPrincipal, 
               MostrarPlantilla.fndPie, MostrarPlantilla.sponsors);
            plantilla1.setVisible(true);
    }//GEN-LAST:event_btn_plantilla1ActionPerformed

    private void btn_plantilla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plantilla2ActionPerformed
 
        Plantilla2 plantilla2 = new Plantilla2(MostrarPlantilla.fndCabecera, 
               MostrarPlantilla.imgCabecera,
                    MostrarPlantilla.fndPrincipal, 
               MostrarPlantilla.imgPrincipal, 
               MostrarPlantilla.fndPie, MostrarPlantilla.sponsors);
            plantilla2.setVisible(true);
    }//GEN-LAST:event_btn_plantilla2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_plantilla1;
    private javax.swing.JButton btn_plantilla2;
    // End of variables declaration//GEN-END:variables
}
