/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

/**
 *
 * @author Miguel
 */
public class CrearCartel extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearCartel
     */
    public CrearCartel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        btn_elegirArchivo = new javax.swing.JButton();
        btn_anadirCabecera = new javax.swing.JButton();
        btn_anadirPrincipal = new javax.swing.JButton();
        btn_anadirPie = new javax.swing.JButton();
        txt_cabecera = new javax.swing.JTextField();
        btn_principal = new javax.swing.JTextField();
        btn_pie = new javax.swing.JTextField();
        cbx_seleccionarSponsor = new javax.swing.JComboBox<>();
        lbl_PrevisualizarSponsor = new javax.swing.JLabel();
        btn_anadirSponsor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_sponsorsSelecionados = new javax.swing.JList<>();
        btn_guardar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_colorFondo = new javax.swing.JButton();
        txt_colorFondo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Crear cartel");

        btn_elegirArchivo.setText("Elegir Archivo");

        btn_anadirCabecera.setText("Añadir Cabecera");

        btn_anadirPrincipal.setText("Añadir Principal");

        btn_anadirPie.setText("Añadir Pie");

        cbx_seleccionarSponsor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_PrevisualizarSponsor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_PrevisualizarSponsor.setText("Previsualizar imagen");
        lbl_PrevisualizarSponsor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_anadirSponsor.setText(">");

        lst_sponsorsSelecionados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lst_sponsorsSelecionados);

        btn_guardar.setText("Guardar");

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_colorFondo.setText("Color del Fondo");
        btn_colorFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorFondoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_elegirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_anadirCabecera, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_anadirPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_anadirPie, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_seleccionarSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_PrevisualizarSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_anadirSponsor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_principal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_pie, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_colorFondo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_salir))
                    .addComponent(txt_colorFondo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cabecera))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_elegirArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_anadirCabecera)
                            .addComponent(txt_cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_anadirPrincipal)
                            .addComponent(btn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_anadirPie)
                            .addComponent(btn_pie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbx_seleccionarSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_PrevisualizarSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btn_anadirSponsor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_colorFondo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_colorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_guardar)
                            .addComponent(btn_salir)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_colorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colorFondoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_colorFondoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anadirCabecera;
    private javax.swing.JButton btn_anadirPie;
    private javax.swing.JButton btn_anadirPrincipal;
    private javax.swing.JButton btn_anadirSponsor;
    private javax.swing.JButton btn_colorFondo;
    private javax.swing.JButton btn_elegirArchivo;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JTextField btn_pie;
    private javax.swing.JTextField btn_principal;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbx_seleccionarSponsor;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_PrevisualizarSponsor;
    private javax.swing.JList<String> lst_sponsorsSelecionados;
    private javax.swing.JTextField txt_cabecera;
    private javax.swing.JTextField txt_colorFondo;
    // End of variables declaration//GEN-END:variables
}
