/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import logica.CrearCartelxml;
import objetos.Cartel;

/**
 *
 * @author Miguel
 */
public class CrearCartel extends javax.swing.JInternalFrame {

    private DefaultListModel modelo;
    private String rutaImagenCabecera = "";
    private String nombreImagenCabecera = "";
    private String rutaImagenPrincipal = "";
    private String nombreImagenPrincipal = "";
    private String rutaImagenPie = "";
    private String nombreImagenPie;

    private Color colorFondo;

    /**
     * Creates new form CrearCartel
     */
    public CrearCartel() {
        initComponents();
        llenarComboSoponsors();
        generarModeloListaSponsors();
    }

    private void generarModeloListaSponsors() {
        modelo = new DefaultListModel();
    }

    private void llenarComboSoponsors() {
        cbx_seleccionarSponsor.addItem("adidas.png");
        cbx_seleccionarSponsor.addItem("cocacola.png");
        cbx_seleccionarSponsor.addItem("rebook.png");
        cbx_seleccionarSponsor.addItem("redbull.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        btn_anadirCabecera = new javax.swing.JButton();
        btn_anadirPrincipal = new javax.swing.JButton();
        btn_anadirPie = new javax.swing.JButton();
        cbx_seleccionarSponsor = new javax.swing.JComboBox<>();
        lbl_PrevisualizarSponsor = new javax.swing.JLabel();
        btn_anadirSponsor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_sponsorsSelecionados = new javax.swing.JList<>();
        btn_guardar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_colorFondo = new javax.swing.JButton();
        txt_colorFondo = new javax.swing.JTextField();
        btn_quitarEsponsorLista = new javax.swing.JButton();
        lbl_cabecera = new javax.swing.JLabel();
        lbl_principal = new javax.swing.JLabel();
        lbl_pie = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        fileChooser.setFileFilter(new MiFiltro());

        setClosable(true);
        setIconifiable(true);
        setTitle("Crear cartel");

        btn_anadirCabecera.setText("Añadir Cabecera");
        btn_anadirCabecera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anadirCabeceraActionPerformed(evt);
            }
        });

        btn_anadirPrincipal.setText("Añadir Principal");
        btn_anadirPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anadirPrincipalActionPerformed(evt);
            }
        });

        btn_anadirPie.setText("Añadir Pie");
        btn_anadirPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anadirPieActionPerformed(evt);
            }
        });

        cbx_seleccionarSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_seleccionarSponsorActionPerformed(evt);
            }
        });

        lbl_PrevisualizarSponsor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_PrevisualizarSponsor.setText("Previsualizar imagen");
        lbl_PrevisualizarSponsor.setAlignmentY(0.0F);
        lbl_PrevisualizarSponsor.setBorder(new javax.swing.border.MatteBorder(null));
        lbl_PrevisualizarSponsor.setPreferredSize(new java.awt.Dimension(98, 94));

        btn_anadirSponsor.setText(">");
        btn_anadirSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anadirSponsorActionPerformed(evt);
            }
        });

        lst_sponsorsSelecionados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(lst_sponsorsSelecionados);

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_colorFondo.setText("Color del Fondo");
        btn_colorFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorFondoActionPerformed(evt);
            }
        });

        btn_quitarEsponsorLista.setText("<");
        btn_quitarEsponsorLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarEsponsorListaActionPerformed(evt);
            }
        });

        lbl_cabecera.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_principal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_pie.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Sponsors");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_seleccionarSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_PrevisualizarSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_anadirSponsor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_quitarEsponsorLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_anadirCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_anadirPrincipal))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_anadirPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_pie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_colorFondo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_salir))
                            .addComponent(txt_colorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_anadirCabecera)
                    .addComponent(btn_anadirPrincipal)
                    .addComponent(btn_anadirPie))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_pie, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbx_seleccionarSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_PrevisualizarSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btn_anadirSponsor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_quitarEsponsorLista))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_colorFondo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_colorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_guardar)
                            .addComponent(btn_salir)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_colorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colorFondoActionPerformed
        ColorChooserDemo elegirColor = new ColorChooserDemo();
        elegirColor.createAndShowGUI();
    }//GEN-LAST:event_btn_colorFondoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void cbx_seleccionarSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_seleccionarSponsorActionPerformed
        lbl_PrevisualizarSponsor.setSize(94, 94);
        ImageIcon imagenSponsor = new ImageIcon("ImagenesEsponsors"
                + System.getProperty("file.separator") + cbx_seleccionarSponsor.getSelectedItem());
        Icon iconoSponsor;
        iconoSponsor = new ImageIcon(imagenSponsor.getImage().getScaledInstance(
                lbl_PrevisualizarSponsor.getWidth(), lbl_PrevisualizarSponsor.getHeight(),
                Image.SCALE_DEFAULT));

        lbl_PrevisualizarSponsor.setIcon(iconoSponsor);
    }//GEN-LAST:event_cbx_seleccionarSponsorActionPerformed

    private void btn_anadirSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anadirSponsorActionPerformed
        if (cbx_seleccionarSponsor.getSelectedIndex() != -1) {
            modelo.addElement(cbx_seleccionarSponsor.getSelectedItem());
            lst_sponsorsSelecionados.setModel(modelo);
        }
    }//GEN-LAST:event_btn_anadirSponsorActionPerformed

    private void btn_quitarEsponsorListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarEsponsorListaActionPerformed
        if (!lst_sponsorsSelecionados.isSelectionEmpty()) {
            modelo.removeElement(lst_sponsorsSelecionados.getSelectedValue());
            lst_sponsorsSelecionados.setModel(modelo);
        }
    }//GEN-LAST:event_btn_quitarEsponsorListaActionPerformed

    private void btn_anadirCabeceraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anadirCabeceraActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            rutaImagenCabecera = file.getAbsolutePath();
            nombreImagenCabecera = file.getName();
            //lbl_previsualizar.setSize(94, 94);
            ImageIcon imagenSponsor = new ImageIcon(rutaImagenCabecera);
            Icon iconoSponsor;
            iconoSponsor = new ImageIcon(imagenSponsor.getImage().getScaledInstance(
                    lbl_cabecera.getWidth(), lbl_cabecera.getHeight(),
                    Image.SCALE_DEFAULT));

            lbl_cabecera.setIcon(iconoSponsor);

        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btn_anadirCabeceraActionPerformed

    private void btn_anadirPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anadirPrincipalActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            rutaImagenPrincipal = file.getAbsolutePath();
            nombreImagenPrincipal = file.getName();
            //lbl_previsualizar.setSize(94, 94);
            ImageIcon imagenSponsor = new ImageIcon(rutaImagenPrincipal);
            Icon iconoSponsor;
            iconoSponsor = new ImageIcon(imagenSponsor.getImage().getScaledInstance(
                    lbl_principal.getWidth(), lbl_principal.getHeight(),
                    Image.SCALE_DEFAULT));

            lbl_principal.setIcon(iconoSponsor);

        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btn_anadirPrincipalActionPerformed

    private void btn_anadirPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anadirPieActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            rutaImagenPie = file.getAbsolutePath();
            nombreImagenPie = file.getName();
            //lbl_previsualizar.setSize(94, 94);
            ImageIcon imagenSponsor = new ImageIcon(rutaImagenPie);
            Icon iconoSponsor;
            iconoSponsor = new ImageIcon(imagenSponsor.getImage().getScaledInstance(
                    lbl_pie.getWidth(), lbl_pie.getHeight(),
                    Image.SCALE_DEFAULT));

            lbl_pie.setIcon(iconoSponsor);

        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btn_anadirPieActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        try {
            Cartel cartel = new Cartel();//Objeto que contiene toda la información del cartel.

            /*
            Al mismo tiempo que creo el cartel tehgo que guardar las imagenes 
            seleccionadas en las carpetas correpondientes dentro del proyecto.
             */
            //Reemplazar si existe y atributos(opciones)
            CopyOption[] options = new CopyOption[]{
                StandardCopyOption.REPLACE_EXISTING,
                StandardCopyOption.COPY_ATTRIBUTES
            };

            Path fromCabecera = Paths.get(rutaImagenCabecera);
            Path toCabecera = Paths.get("ImagenesCabecera"
                    + System.getProperty("file.separator") + nombreImagenCabecera);
            Files.copy(fromCabecera, toCabecera, options);

            cartel.setCabecera(nombreImagenCabecera);

            Path fromPrincipal = Paths.get(rutaImagenPrincipal);
            Path toPrincipal = Paths.get("ImagenesPrincipal"
                    + System.getProperty("file.separator") + nombreImagenPrincipal);
            Files.copy(fromPrincipal, toPrincipal, options);

            cartel.setPrincipal(nombreImagenPrincipal);

            Path formPie = Paths.get(rutaImagenPie);
            Path toPie = Paths.get("ImagenesPie"
                    + System.getProperty("file.separator") + nombreImagenPie);
            Files.copy(formPie, toPie, options);

            cartel.setPie(nombreImagenPie);

            cartel.setColorFondo(colorFondo);
           
            //Los sponsor los Gestiono desde otro sitio del programa. Por lo que
           List<String> listaSponsors = new ArrayList();
           
           for(int i=0;i<lst_sponsorsSelecionados.getModel().getSize();i++){
               listaSponsors.add(lst_sponsorsSelecionados.getModel().getElementAt(i));
           }
            
            cartel.setSponsors(listaSponsors);

            new CrearCartelxml(cartel);

        } catch (Throwable ex) {
            Logger.getLogger(CrearCartel.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("No se creó el cartel ");
        }
      
    }//GEN-LAST:event_btn_guardarActionPerformed
    class MiFiltro extends javax.swing.filechooser.FileFilter {

        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".png");
        }

        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Text documents (*.png)";
        }
    }

    public class ColorChooserDemo extends JPanel
            implements ChangeListener {

        protected JColorChooser tcc;

        public ColorChooserDemo() {
            super(new BorderLayout());

            tcc = new JColorChooser(Color.yellow);
            tcc.getSelectionModel().addChangeListener(this);
            tcc.setBorder(BorderFactory.createTitledBorder(
                    "Choose Text Color"));

            //add(bannerPanel, BorderLayout.CENTER);
            add(tcc, BorderLayout.PAGE_END);
        }

        public void stateChanged(ChangeEvent e) {
            colorFondo = tcc.getColor();
            txt_colorFondo.setBackground(tcc.getColor());
        }

        /**
         * Create the GUI and show it. For thread safety, this method should be
         * invoked from the event-dispatching thread.
         */
        public void createAndShowGUI() {
            //Create and set up the window.
            JFrame frame = new JFrame("ColorChooser");

            frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

            //Create and set up the content pane.
            JComponent newContentPane = new ColorChooserDemo();
            newContentPane.setOpaque(true); //content panes must be opaque
            frame.setContentPane(newContentPane);

            //Display the window.
            frame.pack();
            frame.setVisible(true);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anadirCabecera;
    private javax.swing.JButton btn_anadirPie;
    private javax.swing.JButton btn_anadirPrincipal;
    private javax.swing.JButton btn_anadirSponsor;
    private javax.swing.JButton btn_colorFondo;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_quitarEsponsorLista;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbx_seleccionarSponsor;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_PrevisualizarSponsor;
    private javax.swing.JLabel lbl_cabecera;
    private javax.swing.JLabel lbl_pie;
    private javax.swing.JLabel lbl_principal;
    private javax.swing.JList<String> lst_sponsorsSelecionados;
    private javax.swing.JTextField txt_colorFondo;
    // End of variables declaration//GEN-END:variables
}
